### PR TITLE
Feature/better refresh

### PR DESCRIPTION
**Pull request by dbehnke**
#2 Ok so I believe this satisfies the requirement of refreshing only when mrefd changes.  However I noticed after running it on my server, that mrefd.xml is being written to disk every 20 seconds by mrefd.  But I'll come back to that in a moment.  Let me walk through the changes.

Reflector and Reflector data are new structs in the models file.  This allows us to buffer the reflector data into memory without having to load the mrefd.xml on every request.  Now it will just simply check for the date change on the file when a browser polls the new status endpoint.  If the date changed since last it will update the reflector data in memory by loading new content of the file.

status endpoint .. this is just JSON data that spits out when the last time mrefd.xml was changed.   This allows the browser to then compare with its last status check and determine if it wants to reload the page.

header.html template modified to add a very simple javascript that polls the status endpoint and determine if it should reload the page.  It has a safety trigger also that will reload the page after a minute regardless.

refresh respects the value in .env file and puts that in the template file.

I'm thinking if this pull request is accepted.. at some later phase we look into just updating the section of the page that has changed instead of reloading.. there are some simple javascript framerworks like vue.js or svelte that can just add a little bit of functionality to the page without commiting to some larger framework like react.  My experience on what is best to use is limited there.. i have played with vue.js before with some success. Opinions are welcome on that.

currently this code is running on https://m17.ac8zd.com - and will test with a days worth of traffic tommorow.

re: 20 second always writting mrefd.xml to disk from mrefd.. we may just have to compare the contents somehow to determine if there really is something new.. that could be a little more tricky heh.. it would be nice if mrefd only wrote to that file when something has changed and then the dashboard wouldn't trigger refreshing peoples browsers every 20 seconds.

### CODE REVIEW

**Comment by dbehnke** [comment]
Sample log output
```
[GIN] 2022/10/02 - 01:17:28 | 200 |    1.077933ms |  73.191.206.102 | GET      "/status"
[GIN] 2022/10/02 - 01:17:34 | 200 |     882.146µs |  73.191.206.102 | GET      "/"
2022/10/02 01:18:00 refreshing mrefd data modtime: 2022-10-02 01:17:53.755184038 -0400 EDT, last reflector data file time: 2022-10-02 01:17:23.751159994 -0400 EDT
[GIN] 2022/10/02 - 01:18:00 | 200 |    1.016782ms |  73.191.206.102 | GET      "/status"
2022/10/02 01:18:16 refreshing mrefd data modtime: 2022-10-02 01:18:13.755200056 -0400 EDT, last reflector data file time: 2022-10-02 01:17:53.755184038 -0400 EDT
[GIN] 2022/10/02 - 01:18:16 | 200 |     755.361µs |  73.191.206.102 | GET      "/status"
[GIN] 2022/10/02 - 01:18:23 | 200 |     1.08501ms |  73.191.206.102 | GET      "/"
2022/10/02 01:18:45 refreshing mrefd data modtime: 2022-10-02 01:18:43.759224093 -0400 EDT, last reflector data file time: 2022-10-02 01:18:13.755200056 -0400 EDT
[GIN] 2022/10/02 - 01:18:45 | 200 |     3.13301ms |  73.191.206.102 | GET      "/status"
2022/10/02 01:19:07 refreshing mrefd data modtime: 2022-10-02 01:19:03.763240132 -0400 EDT, last reflector data file time: 2022-10-02 01:18:43.759224093 -0400 EDT
[GIN] 2022/10/02 - 01:19:07 | 200 |    1.111933ms |  73.191.206.102 | GET      "/status"
[GIN] 2022/10/02 - 01:19:13 | 200 |    1.058268ms |  73.191.206.102 | GET      "/"
2022/10/02 01:19:37 refreshing mrefd data modtime: 2022-10-02 01:19:33.767264176 -0400 EDT, last reflector data file time: 2022-10-02 01:19:03.763240132 -0400 EDT
[GIN] 2022/10/02 - 01:19:37 | 200 |    1.021932ms |  73.191.206.102 | GET      "/status"
2022/10/02 01:19:54 refreshing mrefd data modtime: 2022-10-02 01:19:53.771280197 -0400 EDT, last reflector data file time: 2022-10-02 01:19:33.767264176 -0400 EDT
[GIN] 2022/10/02 - 01:19:54 | 200 |     1.00153ms |  73.191.206.102 | GET      "/status"
[GIN] 2022/10/02 - 01:20:01 | 200 |    1.003834ms |  73.191.206.102 | GET      "/"
```

**Review by kc1awv — COMMENTED** [review]
I really appreciate using an environment variable for the log file, this was something that I was going to put in as another task for myself, so thank you. 

I noticed jQuery 1.12. Is there a reason for that, vs. 3.6.1? jQuery 3 has a few more useful features that may come into play, `$.ajax` , `$.when`, `.data()` and keeps in line with HTML5 compatibility. Also, is 5kB smaller. Just a thought.

Let me know your thoughts, and I'll approve the changes.

**Comment by dbehnke** [comment]
yeah let me bump to jquery 3 and see if its compatible or if need to make changes.  It was just the first cdn link I saw.  Then we can merge this and I'll see if maybe i can do some things with javascript so we don't have to reload the page.  Hopefully not add to much complexity.. but would be really cool to get rid of that blink effect.

**Comment by dbehnke** [comment]
ok this has been updated to use jquery 3.6.1 and still works

**Comment by kc1awv** [comment]
Sounds good!

**Pull request merged**
