### PR TITLE
feat: M17 Logo next to reflector name, document title for tx/idle

### PR DESCRIPTION
**Pull request by dbehnke**
* M17 Logo next to the reflector name in the titlebar
* Document title now changes to the Reflector Name when idle, and TX: Callsign when first row has someone transmitting. (allows one to see who's tx on a browser tab)

this implements #30

### CODE REVIEW

**Review by n7tae — COMMENTED** [review]
With that almost black background, it's very hard to see the M. It looks to me like a red 17 with a smudge to the left. I think you either need to lighten up the background, at least around the logo, or, even better, use a logo with a bright white M, if one exists.

**Comment by dbehnke** [comment]
now has a white circle for the logo.

image

Screenshot 2023-01-21 at 4 21 44 PM

**Comment by dbehnke** [comment]
now with more spacing between logo and title.. 
image

**Review by kc1awv — APPROVED** [review]
I like it!

**Pull request merged**
